export const SERVICES = [
  { title: "Web Development", slug: "web-development", icon: "Globe", shortDescription: "High-performance, scalable websites built with modern frameworks." },
  { title: "Mobile App Development", slug: "mobile-app-development", icon: "Smartphone", shortDescription: "Native and cross-platform Android & iOS applications." },
  { title: "SaaS Product Development", slug: "saas-product-development", icon: "Cloud", shortDescription: "End-to-end SaaS platforms from MVP to enterprise scale." },
  { title: "CRM Development", slug: "crm-development", icon: "Users", shortDescription: "Custom CRM systems tailored to your sales workflow." },
  { title: "ERP Development", slug: "erp-development", icon: "Building2", shortDescription: "Enterprise resource planning for operations excellence." },
  { title: "AI Solutions & Automation", slug: "ai-solutions-automation", icon: "Brain", shortDescription: "Intelligent automation and AI-powered business solutions." },
  { title: "Custom Software Development", slug: "custom-software-development", icon: "Code2", shortDescription: "Bespoke software engineered for your unique requirements." },
  { title: "E-Commerce Development", slug: "ecommerce-development", icon: "ShoppingCart", shortDescription: "Conversion-optimized online stores and marketplaces." },
  { title: "Cloud Solutions", slug: "cloud-solutions", icon: "Server", shortDescription: "AWS, Azure, and GCP cloud architecture and migration." },
  { title: "API Development", slug: "api-development", icon: "Plug", shortDescription: "RESTful and GraphQL APIs with enterprise security." },
  { title: "DevOps Services", slug: "devops-services", icon: "GitBranch", shortDescription: "CI/CD pipelines, infrastructure as code, and monitoring." },
  { title: "Maintenance & Support", slug: "maintenance-support", icon: "Wrench", shortDescription: "24/7 application maintenance and technical support." },
  { title: "IT Consulting", slug: "it-consulting", icon: "Lightbulb", shortDescription: "Strategic technology consulting for digital transformation." },
  { title: "SEO Services", slug: "seo-services", icon: "Search", shortDescription: "Data-driven SEO to dominate search rankings." },
  { title: "Digital Marketing", slug: "digital-marketing", icon: "TrendingUp", shortDescription: "Full-funnel digital marketing campaigns that convert." },
  { title: "Social Media Marketing", slug: "social-media-marketing", icon: "Share2", shortDescription: "Brand growth across all major social platforms." },
  { title: "UI/UX Design", slug: "ui-ux-design", icon: "Palette", shortDescription: "User-centered interfaces that delight and convert." },
  { title: "Figma Design", slug: "figma-design", icon: "Layout", shortDescription: "Pixel-perfect Figma designs and design systems." },
  { title: "Branding", slug: "branding", icon: "Award", shortDescription: "Complete brand identity and positioning strategy." },
  { title: "Logo Design", slug: "logo-design", icon: "PenTool", shortDescription: "Memorable logos that define your brand essence." },
  { title: "Poster & Banner Design", slug: "poster-banner-design", icon: "Image", shortDescription: "Stunning visual assets for marketing campaigns." },
] as const;
